In [ ]:
# basics of tensorflow codes

In [ ]:
import tensorflow as tf

In [ ]:
print (tf.__version__)

2.15.0


In [ ]:
# create first tensor with tf.constant()
scalar=tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [ ]:
# check number of dimensions of tensors(ndim stands for number of dimensions)
scalar.ndim

0

In [ ]:
#create a vector
vector=tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [ ]:
vector.ndim

1

In [ ]:
#create a matrix(matrix has more than 1)
matrix=tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [ ]:
matrix.ndim

2

In [ ]:
#create another matrix
another_matrix=tf.constant([[10.,7.],
                            [3.,4.],
                            [5.,4.]], dtype=tf.float16)
another_matrix

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 3.,  4.],
       [ 5.,  4.]], dtype=float16)>

In [ ]:
# number of dimensions
another_matrix.ndim

2

In [ ]:
# let's create a tensor
tensor=tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]],
                    [[13,14,15],[16,17,18]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
tensor.ndim

3

creating tensors with tf.variable


In [ ]:
changeable_tensor=tf.Variable([10,7])
unchangeable_tensor=tf.constant([10,7])
changeable_tensor, unchangeable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

# let's try to change one of the elements in our changeable tensor


In [ ]:
changeable_tensor[0]=7
changeable_tensor

TypeError: 'ResourceVariable' object does not support item assignment

In [ ]:
#use .assign()
changeable_tensor[0].assign(7)
changeable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

In [ ]:
#lets try change number in unchangeable_tensor
unchangeable_tensor[0].assign(7)

unchangeable_tensor

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

Random tensors

In [ ]:
#create 2 random tensors
random_1=tf.random.Generator.from_seed(42) #set seed for reproducibility
random_1=random_1.normal(shape=(3,2))
random_2=tf.random.Generator.from_seed(42)
random_2=random_2.normal(shape=(3,2))

#are they equal
random_1, random_2, random_1==random_2

(<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=float32, numpy=
 array([[-0.7565803 , -0.06854702],
        [ 0.07595026, -1.2573844 ],
        [-0.23193763, -1.8107855 ]], dtype=float32)>,
 <tf.Tensor: shape=(3, 2), dtype=bool, numpy=
 array([[ True,  True],
        [ True,  True],
        [ True,  True]])>)

shuffle the order of elements in a tensor

In [ ]:
#shuffle a tensor
not_shuffled=tf.constant([[10,7],
                        [3,4],
                        [2,5]])
#shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 2,  5],
       [ 3,  4]], dtype=int32)>

In [ ]:
tf.random.set_seed(42)
#shuffle our non_shuffled tensor
tf.random.shuffle(not_shuffled, seed=42)

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [ ]:
ran1=tf.random.Generator.from_seed(42)
ran1=tf.random.normal(shape=(4,3))
ran1

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.3274685 , -0.8426258 ,  0.3194337 ],
       [-1.4075519 , -2.3880599 , -1.0392479 ],
       [-0.5573232 ,  0.539707  ,  1.6994323 ],
       [ 0.28893656, -1.5066116 , -0.26454744]], dtype=float32)>

In [ ]:
tf.random.shuffle(ran1)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.5573232 ,  0.539707  ,  1.6994323 ],
       [ 0.3274685 , -0.8426258 ,  0.3194337 ],
       [ 0.28893656, -1.5066116 , -0.26454744],
       [-1.4075519 , -2.3880599 , -1.0392479 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(42)
tf.random.shuffle(ran1, seed=42)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-1.4075519 , -2.3880599 , -1.0392479 ],
       [-0.5573232 ,  0.539707  ,  1.6994323 ],
       [ 0.3274685 , -0.8426258 ,  0.3194337 ],
       [ 0.28893656, -1.5066116 , -0.26454744]], dtype=float32)>

In [ ]:
ran2=tf.random.Generator.from_seed(42)
ran2=tf.random.normal(shape=(4,3))
ran2

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[ 0.3274685 , -0.8426258 ,  0.3194337 ],
       [-1.4075519 , -2.3880599 , -1.0392479 ],
       [-0.5573232 ,  0.539707  ,  1.6994323 ],
       [ 0.28893656, -1.5066116 , -0.26454744]], dtype=float32)>

In [ ]:
tf.random.shuffle(ran2)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-0.5573232 ,  0.539707  ,  1.6994323 ],
       [ 0.3274685 , -0.8426258 ,  0.3194337 ],
       [ 0.28893656, -1.5066116 , -0.26454744],
       [-1.4075519 , -2.3880599 , -1.0392479 ]], dtype=float32)>

In [ ]:
tf.random.set_seed(42) #setting the grobal random seed
tf.random.shuffle(ran2, seed=42)

<tf.Tensor: shape=(4, 3), dtype=float32, numpy=
array([[-1.4075519 , -2.3880599 , -1.0392479 ],
       [-0.5573232 ,  0.539707  ,  1.6994323 ],
       [ 0.3274685 , -0.8426258 ,  0.3194337 ],
       [ 0.28893656, -1.5066116 , -0.26454744]], dtype=float32)>

In [ ]:
#other ways to make tensors


In [ ]:
#create a tensor of all ones
tf.ones([10,7], tf.float32)

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [ ]:
# create a tensor of all zeros
tf.zeros(shape=(3,2))

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[0., 0.],
       [0., 0.],
       [0., 0.]], dtype=float32)>

In [ ]:
# u can also turn numpy arrays into tensors


In [ ]:
import numpy as np
numpy_A=np.arange(1,25, dtype=np.int32) #make a numpy array between 1 and 25

numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [ ]:
A=tf.constant(numpy_A,shape=(2,3,4))
B=tf.constant(numpy_A)
A,B

(<tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>,
 <tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>)

# Getting information from our tensors
when dealing with tensors you must be aware of the following terms.
* shape: number of elements in the tensor. eg: tensor.shape
* rank: number of dimensions. eg: tensor.ndim
* axis: getting a value eg tensor[0], tensor[:,1]
* size: total number of items in the tensor. eg: tf.size(tensor)


In [ ]:
#creating rank 4 tensor( 4 dimensions )
rank_4_tensor=tf.zeros(shape=(2,3,4,5))
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [ ]:
rank_4_tensor.shape, rank_4_tensor.ndim,tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [ ]:
# Get various attributes from our tensor
print('Data type of every element:',rank_4_tensor.dtype)
print('NUmber of dimensions(rank)',rank_4_tensor.ndim)
print('shape of our tensor:',rank_4_tensor.shape)
print('Elements along 0 axis:',rank_4_tensor.shape[0])
print('Elements on the last axis:', rank_4_tensor.shape[-1])
print('Total number of elemenets in our tensor', tf.size(rank_4_tensor))
print('Total number of elemenets in our tensor', tf.size(rank_4_tensor).numpy())

Data type of every element: <dtype: 'float32'>
NUmber of dimensions(rank) 4
shape of our tensor: (2, 3, 4, 5)
Elements along 0 axis: 2
Elements on the last axis: 5
Total number of elemenets in our tensor tf.Tensor(120, shape=(), dtype=int32)
Total number of elemenets in our tensor 120


indexing tensors as python lists

In [ ]:
# Get first 2 elements of each dimension
some_list=[1,2,3,4,5,6]
some_list[:2],rank_4_tensor[:2,:2,:2,:2]


([1, 2],
 <tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
 array([[[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]],
 
 
        [[[0., 0.],
          [0., 0.]],
 
         [[0., 0.],
          [0., 0.]]]], dtype=float32)>)

In [ ]:
# Get the first element from each dimension except the last one
rank_4_tensor[:1,:1,:1,:]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [ ]:
rank_4_tensor[:1,:1,:,:1]

<tf.Tensor: shape=(1, 1, 4, 1), dtype=float32, numpy=
array([[[[0.],
         [0.],
         [0.],
         [0.]]]], dtype=float32)>

In [ ]:
# create a 2 rank rensor(2 dimensions)
rank_2_tensor=tf.constant([[10,7],
                           [3,4]])
rank_2_tensor.shape, rank_2_tensor.ndim, tf.size(rank_2_tensor)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [ ]:
# Get last item of each row of our rank 2 tensor
rank_2_tensor[:,-1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [ ]:
# add in an extr dimension to our tensor
rank_3_tensor=rank_2_tensor[...,tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
# alternative to the newaxis
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [ ]:
tf.expand_dims(rank_2_tensor, axis=1)

<tf.Tensor: shape=(2, 1, 2), dtype=int32, numpy=
array([[[10,  7]],

       [[ 3,  4]]], dtype=int32)>

In [ ]:
rank_2_tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
### manipurating tensors

In [ ]:
# basic operations
# addition
tensor=tf.constant([[10,7],[3,4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
tensor=tensor + 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [ ]:
#substraction
tensor= tensor - 10
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4]], dtype=int32)>

In [ ]:
# multiplication
tensor=tensor + 10
tensor,tensor *2

(<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[20, 17],
        [13, 14]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[40, 34],
        [26, 28]], dtype=int32)>)

In [ ]:
# we can use tensorflow builtin-function too
tf.multiply(tensor,20)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[400, 340],
       [260, 280]], dtype=int32)>

In [ ]:
tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

***matrix maltiplication***

In [ ]:
# matrix multiplications in tensorflow
print(tensor)
tf.matmul(tensor,tensor)

tf.Tensor(
[[20 17]
 [13 14]], shape=(2, 2), dtype=int32)


<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [ ]:
tensor @ tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[621, 578],
       [442, 417]], dtype=int32)>

In [ ]:
# create a tensor of (3,2) shape
X=tf.constant([[1,2],
              [3,4],
              [5,6]])
# create a tensor of (3,2) shape
Y=tf.constant([[7,8],
               [9,10],
               [11,12]])
X,Y

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4],
        [5, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>)

In [ ]:
# try to matrix multiply them
tf.matmul(X,Y)

InvalidArgumentError: {{function_node __wrapped__MatMul_device_/job:localhost/replica:0/task:0/device:CPU:0}} Matrix size-incompatible: In[0]: [3,2], In[1]: [3,2] [Op:MatMul] name: 

In [ ]:
Y

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[ 7,  8],
       [ 9, 10],
       [11, 12]], dtype=int32)>

In [ ]:
# lets change the shape of Y tensor
tf.reshape(Y,shape=(2,3))


<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[ 7,  8,  9],
       [10, 11, 12]], dtype=int32)>

In [ ]:
# try to multiply X and reshaped Y
X @ tf.reshape(Y,shape=(2,3))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
tf.reshape(X,shape=(2,3))

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]], dtype=int32)>

In [ ]:
# try change the value of X instead of Y
tf.matmul(tf.reshape(X,shape=(2,3)),Y)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 58,  64],
       [139, 154]], dtype=int32)>

In [ ]:
# can do the same for transpose
tf.transpose(X)

<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
array([[1, 3, 5],
       [2, 4, 6]], dtype=int32)>

In [ ]:
tf.transpose(tf.reshape(X,shape=(2,3)))

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]], dtype=int32)>

In [ ]:
# try matrix multiplication with transpose rather than reshape
tf.transpose(X),Y,tf.matmul(tf.transpose(X),Y)

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[1, 3, 5],
        [2, 4, 6]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[ 7,  8],
        [ 9, 10],
        [11, 12]], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[ 89,  98],
        [116, 128]], dtype=int32)>)

** the dot product **
 we can use
 *tf.matmul()
 *tf.tensordot()

In [ ]:
#perform a dot product on X and Y( requires X or Y to be transposed)
tf.tensordot(tf.transpose(X),Y, axes=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 89,  98],
       [116, 128]], dtype=int32)>

In [ ]:
# perfrom matrix multiplication Y transposed
tf.matmul(X, tf.transpose(Y))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 23,  29,  35],
       [ 53,  67,  81],
       [ 83, 105, 127]], dtype=int32)>

In [ ]:
tf.matmul(X,tf.reshape(Y,shape=(2,3)))

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[ 27,  30,  33],
       [ 61,  68,  75],
       [ 95, 106, 117]], dtype=int32)>

In [ ]:
# check the values of y, reshaped y and transposed y
print('Normal y:')
print(Y,'\n')

print('y reshaped to (2,3):')
print(tf.reshape(Y,shape=(2,3)),'\n')

print('y transposed:')
print(tf.transpose(Y))

Normal y:
tf.Tensor(
[[ 7  8]
 [ 9 10]
 [11 12]], shape=(3, 2), dtype=int32) 

y reshaped to (2,3):
tf.Tensor(
[[ 7  8  9]
 [10 11 12]], shape=(2, 3), dtype=int32) 

y transposed:
tf.Tensor(
[[ 7  9 11]
 [ 8 10 12]], shape=(2, 3), dtype=int32)


In [ ]:
### change the datatype of the tensor
# create a new tensor
B=tf.constant([1.7,7.4])
B.dtype

tf.float32

In [ ]:
C=tf.constant([7,10])
C.dtype

tf.int32

In [ ]:
# change from float32 to float16 (reduced precision)
B=tf.cast(B,dtype=tf.float16)
B,B.dtype

(<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>,
 tf.float16)

In [ ]:
E=tf.cast(C,dtype=tf.float16)
E

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([ 7., 10.], dtype=float16)>

Aggregating tensors:
condensing tensors from multiple values down to smaller amount of values

In [ ]:
# getting the absolute values
D=tf.constant([-7,-10])
D

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ -7, -10], dtype=int32)>

In [ ]:
# getting absolute values
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [ ]:
# more forms of aggregation
# get minimum
# get maximum
# get mean of a tensor
# get sum of the tensor


In [ ]:
# create a random tensor with values between 0 and 100 of size 50
E=tf.constant(np.random.randint(0,100,size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([37, 80, 62, 70, 42, 54, 91, 47,  3, 91, 45, 14, 85, 82, 73, 15, 41,
       46, 67, 87, 80, 38,  3, 69, 10, 78, 19, 80, 58, 61, 59, 25, 29, 82,
       61, 53, 48, 44, 63, 48, 99, 32, 26, 79, 97, 31, 72,  4,  8, 89])>

In [ ]:
tf.size(E).numpy(),E.ndim, E.shape

(50, 1, TensorShape([50]))

In [ ]:
# fin minimum
tf.reduce_min(E)

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [ ]:
np.min(E)

3

In [ ]:
# find maximum
tf.reduce_max(E)

<tf.Tensor: shape=(), dtype=int64, numpy=99>

In [ ]:
# find mean
tf.reduce_mean(E)

<tf.Tensor: shape=(), dtype=int64, numpy=53>

In [ ]:
#find sum
tf.reduce_sum(E)

<tf.Tensor: shape=(), dtype=int64, numpy=2677>

In [ ]:
# to find the variance we need to firstly access tensorflow probability
import tensorflow_probability as tfp
tfp.stats.variance(E)

<tf.Tensor: shape=(), dtype=int64, numpy=737>

In [ ]:
# find standard deviation
tf.math.reduce_std(tf.cast(E,dtype=tf.float32))

<tf.Tensor: shape=(), dtype=float32, numpy=27.158949>

In [ ]:
tf.math.reduce_variance(tf.cast(E,dtype=tf.float32))


<tf.Tensor: shape=(), dtype=float32, numpy=737.60846>

** Find the positional maximum and minimum **

In [ ]:
# create a new tensor to find positional minimum and maximum
tf.random.set_seed(42)
F=tf.random.uniform(shape=[50])
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

In [ ]:
# find index of  the positional maximum
tf.argmax(F)

<tf.Tensor: shape=(), dtype=int64, numpy=42>

In [ ]:
# value of the index of the  positional maximum
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9671384>

In [ ]:
# find the positional minimum
tf.argmin(F)

<tf.Tensor: shape=(), dtype=int64, numpy=16>

In [ ]:
# find the value of the min
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.009463668>

### squeezing a tensor (removing all single dimensions)

In [ ]:
# create a tensor to squeeze
tf.random.set_seed(42)
G=tf.constant(tf.random.uniform(shape=[50]),shape=(1,1,1,1,50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [ ]:
G.shape

TensorShape([1, 1, 1, 1, 50])

In [ ]:
G_squeezed=tf.squeeze(G)
G_squeezed, G_squeezed.shape

(<tf.Tensor: shape=(50,), dtype=float32, numpy=
 array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
        0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
        0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
        0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
        0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
        0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
        0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
        0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
        0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
        0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
       dtype=float32)>,
 TensorShape([50]))

*** one hot encoding ***

In [ ]:
# create a list of indecies
some_list=[0,1,2,3]
#one_hot encode our list
tf.one_hot(some_list,depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>

In [ ]:
# specify custom values or one hot encoding
tf.one_hot(some_list, depth=4, on_value="yo i love deep learning", off_value="i also like to dance")

<tf.Tensor: shape=(4, 4), dtype=string, numpy=
array([[b'yo i love deep learning', b'i also like to dance',
        b'i also like to dance', b'i also like to dance'],
       [b'i also like to dance', b'yo i love deep learning',
        b'i also like to dance', b'i also like to dance'],
       [b'i also like to dance', b'i also like to dance',
        b'yo i love deep learning', b'i also like to dance'],
       [b'i also like to dance', b'i also like to dance',
        b'i also like to dance', b'yo i love deep learning']],
      dtype=object)>

squaring, log, squareroot

In [ ]:
# create a tensor
H= tf.range(1,10
            )
H

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=int32)>

In [ ]:
# Square it
tf.square(H)

<tf.Tensor: shape=(9,), dtype=int32, numpy=array([ 1,  4,  9, 16, 25, 36, 49, 64, 81], dtype=int32)>

In [ ]:
# find the squareroot
tf.sqrt(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([1.       , 1.4142135, 1.7320508, 2.       , 2.236068 , 2.4494898,
       2.6457512, 2.828427 , 3.       ], dtype=float32)>

In [ ]:
# find the log
tf.math.log(tf.cast(H,dtype=tf.float32))

<tf.Tensor: shape=(9,), dtype=float32, numpy=
array([0.       , 0.6931472, 1.0986123, 1.3862944, 1.609438 , 1.7917595,
       1.9459102, 2.0794415, 2.1972246], dtype=float32)>

Tensors and NumPy

In [ ]:
# create a tensor directly from a NumPy array
J=tf.constant(np.array([3.,7.,10.]))
J

<tf.Tensor: shape=(3,), dtype=float64, numpy=array([ 3.,  7., 10.])>

In [ ]:
# convert a tensor back to a NumPy array
np.array(J),type(np.array(J))

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# convert a tensor to NumPy array
J.numpy(),type(J.numpy())

(array([ 3.,  7., 10.]), numpy.ndarray)

In [ ]:
# the default types of each are slightly different
numpy_J=tf.constant(np.array([3.,7.,10.]))
tensor_J=tf.constant([3.,7.,10.])
# check the data types
numpy_J.dtype,tensor_J.dtype

(tf.float64, tf.float32)